user  nginx;
worker_processes  auto;

events { worker_connections 1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  # sane defaults
  sendfile        on;
  tcp_nopush      on;
  tcp_nodelay     on;
  keepalive_timeout  65;
  server_tokens off;

  # logs (container stdout/stderr)
  access_log  /dev/stdout;
  error_log   /dev/stderr warn;

  # include rendered vhosts
  include /etc/nginx/conf.d/*.conf;
}
